{
  "smartbugs_completed": true,
  "analyzer_results": {
    "mythril-0.23.15": {
      "successfull_analysis": true,
      "errors": [],
      "vulnerability_findings": []
    },
    "oyente": {
      "successfull_analysis": true,
      "errors": [],
      "vulnerability_findings": []
    },
    "slither": {
      "successfull_analysis": true,
      "errors": [
        "EXIT_CODE_2"
      ],
      "vulnerability_findings": [
        {
          "name": "external-function",
          "vulnerability_from_line": 7,
          "vulnerability_to_line": 14,
          "vulnerability_code": "    function withdrawBalance() public {\n        require(!locked[msg.sender]); //check if the user is already in a transaction\n        uint amountToWithdraw = userBalances[msg.sender];\n        userBalances[msg.sender] = 0;\n        locked[msg.sender] = true; //set the user to be in a transaction\n        msg.sender.transfer(amountToWithdraw);\n        locked[msg.sender] = false; //set the user to be out of a transaction",
          "message": "Reentrancy_secure.withdrawBalance (patch_1.sol#7-14) should be declared external\n"
        },
        {
          "name": "naming-convention",
          "vulnerability_from_line": 3,
          "vulnerability_to_line": 15,
          "vulnerability_code": "contract Reentrancy_secure {\n    mapping(address => uint) private userBalances;\n    mapping(address => bool) private locked;\n\n    function withdrawBalance() public {\n        require(!locked[msg.sender]); //check if the user is already in a transaction\n        uint amountToWithdraw = userBalances[msg.sender];\n        userBalances[msg.sender] = 0;\n        locked[msg.sender] = true; //set the user to be in a transaction\n        msg.sender.transfer(amountToWithdraw);\n        locked[msg.sender] = false; //set the user to be out of a transaction\n    }",
          "message": "Contract 'Reentrancy_secure' (patch_1.sol#3-15) is not in CapWords\n"
        }
      ]
    }
  }
}