{
  "smartbugs_completed": true,
  "analyzer_results": {
    "oyente": {
      "successfull_analysis": true,
      "errors": [],
      "vulnerability_findings": [
        {
          "name": "Callstack Depth Attack Vulnerability",
          "vulnerability_from_line": 22,
          "vulnerability_to_line": null,
          "vulnerability_code": "            contract_address.call(id, msg.sender, tos[i], vs[i]);",
          "message": null
        },
        {
          "name": "Integer Overflow",
          "vulnerability_from_line": 12,
          "vulnerability_to_line": null,
          "vulnerability_code": "    function transfer(",
          "message": null
        }
      ]
    },
    "slither": {
      "successfull_analysis": true,
      "errors": [
        "EXIT_CODE_6"
      ],
      "vulnerability_findings": [
        {
          "name": "calls-loop",
          "vulnerability_from_line": 22,
          "vulnerability_to_line": null,
          "vulnerability_code": "            contract_address.call(id, msg.sender, tos[i], vs[i]);",
          "message": "AirDropContract.transfer has external calls inside a loop:\n\t- contract_address.call(id,msg.sender,tos[i],vs[i]) (0xa1fceeff3acc57d257b917e30c4df661401d6431.sol#22)\n"
        },
        {
          "name": "external-function",
          "vulnerability_from_line": 12,
          "vulnerability_to_line": 25,
          "vulnerability_code": "    function transfer(\n        address contract_address,\n        address[] tos,\n        uint[] vs\n    ) public validAddress(contract_address) returns (bool) {\n        require(tos.length > 0);\n        require(vs.length > 0);\n        require(tos.length == vs.length);\n        bytes4 id = bytes4(keccak256(\"transferFrom(address,address,uint256)\"));\n        for (uint i = 0; i < tos.length; i++) {\n            contract_address.call(id, msg.sender, tos[i], vs[i]);\n        }\n        return true;",
          "message": "AirDropContract.transfer (0xa1fceeff3acc57d257b917e30c4df661401d6431.sol#12-25) should be declared external\n"
        },
        {
          "name": "solc-version",
          "vulnerability_from_line": 1,
          "vulnerability_to_line": null,
          "vulnerability_code": "pragma solidity ^0.4.18;",
          "message": "Detected issues with version pragma in 0xa1fceeff3acc57d257b917e30c4df661401d6431.sol:\n\t- pragma solidity^0.4.18 (0xa1fceeff3acc57d257b917e30c4df661401d6431.sol#1): it allows old versions\n"
        },
        {
          "name": "low-level-calls",
          "vulnerability_from_line": 12,
          "vulnerability_to_line": 25,
          "vulnerability_code": "    function transfer(\n        address contract_address,\n        address[] tos,\n        uint[] vs\n    ) public validAddress(contract_address) returns (bool) {\n        require(tos.length > 0);\n        require(vs.length > 0);\n        require(tos.length == vs.length);\n        bytes4 id = bytes4(keccak256(\"transferFrom(address,address,uint256)\"));\n        for (uint i = 0; i < tos.length; i++) {\n            contract_address.call(id, msg.sender, tos[i], vs[i]);\n        }\n        return true;",
          "message": "Low level call in AirDropContract.transfer (0xa1fceeff3acc57d257b917e30c4df661401d6431.sol#12-25):\n\t-contract_address.call(id,msg.sender,tos[i],vs[i]) 0xa1fceeff3acc57d257b917e30c4df661401d6431.sol#22\n"
        },
        {
          "name": "naming-convention",
          "vulnerability_from_line": 4,
          "vulnerability_to_line": null,
          "vulnerability_code": "    function AirDropContract() public {}",
          "message": "Function 'AirDropContract.AirDropContract' (0xa1fceeff3acc57d257b917e30c4df661401d6431.sol#4) is not in mixedCase\n"
        },
        {
          "name": "naming-convention",
          "vulnerability_from_line": 13,
          "vulnerability_to_line": null,
          "vulnerability_code": "        address contract_address,",
          "message": "Parameter 'contract_address' of AirDropContract.transfer (0xa1fceeff3acc57d257b917e30c4df661401d6431.sol#13) is not in mixedCase\n"
        }
      ]
    },
    "mythril-0.23.15": {
      "successfull_analysis": true,
      "errors": [],
      "vulnerability_findings": [
        {
          "name": "External Call To User-Supplied Address (SWC 107)",
          "vulnerability_from_line": 22,
          "vulnerability_to_line": null,
          "vulnerability_code": "            contract_address.call(id, msg.sender, tos[i], vs[i]);",
          "message": "A call to a user-supplied address is executed.\nAn external message call to an address specified by the caller is executed. Note that the callee account might contain arbitrary code and could re-enter any function within this contract. Reentering the contract in an intermediate state may lead to unexpected behaviour. Make sure that no state modifications are executed after this call and/or reentrancy guards are in place.\nClassification: SWC-107"
        },
        {
          "name": "Multiple Calls in a Single Transaction (SWC 113)",
          "vulnerability_from_line": 22,
          "vulnerability_to_line": null,
          "vulnerability_code": "            contract_address.call(id, msg.sender, tos[i], vs[i]);",
          "message": "Multiple calls are executed in the same transaction.\nThis call is executed following another call within the same transaction. It is possible that the call never gets executed if a prior call fails permanently. This might be caused intentionally by a malicious callee. If possible, refactor the code such that each transaction only executes one external call or make sure that all callees can be trusted (i.e. they\u2019re part of your own codebase).\nClassification: SWC-113"
        },
        {
          "name": "Unchecked return value from external call. (SWC 104)",
          "vulnerability_from_line": 22,
          "vulnerability_to_line": null,
          "vulnerability_code": "            contract_address.call(id, msg.sender, tos[i], vs[i]);",
          "message": "The return value of a message call is not checked.\nExternal calls return a boolean value. If the callee halts with an exception, 'false' is returned and execution continues in the caller. The caller should check whether an exception happened and react accordingly to avoid unexpected behavior. For example it is often desirable to wrap external calls in require() so the transaction is reverted if the call fails.\nClassification: SWC-104"
        }
      ]
    }
  }
}