{
  "smartbugs_completed": true,
  "analyzer_results": {
    "mythril-0.23.15": {
      "successfull_analysis": true,
      "errors": [],
      "vulnerability_findings": []
    },
    "slither": {
      "successfull_analysis": true,
      "errors": [
        "EXIT_CODE_4"
      ],
      "vulnerability_findings": [
        {
          "name": "arbitrary-send",
          "vulnerability_from_line": 8,
          "vulnerability_to_line": 11,
          "vulnerability_code": "    function solve(string memory solution) public {\n        require(hash == keccak256(bytes(solution)));\n        msg.sender.transfer(1000 ether);",
          "message": "FindThisHash.solve (patch_18.sol#8-11) sends eth to arbitrary user\n\tDangerous calls:\n\t- msg.sender.transfer(1000000000000000000000) (patch_18.sol#10)\n"
        },
        {
          "name": "external-function",
          "vulnerability_from_line": 8,
          "vulnerability_to_line": 11,
          "vulnerability_code": "    function solve(string memory solution) public {\n        require(hash == keccak256(bytes(solution)));\n        msg.sender.transfer(1000 ether);",
          "message": "FindThisHash.solve (patch_18.sol#8-11) should be declared external\n"
        },
        {
          "name": "solc-version",
          "vulnerability_from_line": 1,
          "vulnerability_to_line": null,
          "vulnerability_code": "pragma solidity ^0.5.16;",
          "message": "Detected issues with version pragma in patch_18.sol:\n\t- pragma solidity^0.5.16 (patch_18.sol#1): it allows old versions\n"
        },
        {
          "name": "naming-convention",
          "vulnerability_from_line": 4,
          "vulnerability_to_line": null,
          "vulnerability_code": "    bytes32 public constant hash = 0xb5b5b97fafd9855eec9b41f74dfb6c38f5951141f9a3ecd7f44d5479b630ee0a;",
          "message": "Constant 'FindThisHash.hash' (patch_18.sol#4) is not in UPPER_CASE_WITH_UNDERSCORES\n"
        }
      ]
    },
    "oyente": {
      "successfull_analysis": false,
      "errors": [
        "exception (RuntimeError: Source map error, unknown name(SHR) or instr_name(INVALID))"
      ],
      "vulnerability_findings": []
    }
  }
}